replicaCount: 2

image:
  repository: deekshithsn/zuul
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


service:
  type: NodePort
  port: 9999
  name: zuul
  targetport: 9999
  nodeport: 32470

container:
  name: zuul-api-gateway

cpa:
  podaffinity:
    requiredDuringShedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpessions:
        - key: app
          operator: In 
          values:
          - react-ui
    topologyKey: "kubernetes.io/hostname"
      