replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


service:
  type: NodePort
  port: 80
  name: cart
  targetport: 80

container:
  name: carts